# Generated by Django 4.2.11 on 2024-03-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
